apiVersion: v1
kind: PersistentVolume
metadata:
  name: localpvauthentication
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/jasna/PyCharmProjects/IEP/kubernetes/authentication/mysql"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentication-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeName: localpvauthentication
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: authentication-db-secret
type: Opaque
data:
  password: cm9vdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-db-deployment
  labels:
    app: authentication-db
    authentication-network: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-db
  template:
    metadata:
      labels:
        app: authentication-db
    spec:
      volumes:
        - name: authentication-db-storage
          persistentVolumeClaim:
            claimName: authentication-db-pvc
      containers:
        - name: authentication-db
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentication-db-secret
                  key: password
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: authentication-db-storage
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-db-service
spec:
  selector:
    app: authentication-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-db-configmap
data:
  authentication-db-url: authentication-db-service
---
apiVersion: v1
kind: Pod
metadata:
  name: authentication-db-migration
  labels:
    authentication-network: "true"
spec:
  containers:
    - name: authenticationdbmigration
      image: authenticationdbmigration
      imagePullPolicy: IfNotPresent
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: authentication-db-configmap
              key: authentication-db-url
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  labels:
    app: authentication
    authentication-network: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: authentication
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: authentication-db-configmap
                  key: authentication-db-url
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: LoadBalancer
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authentication-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              authentication-network: "true"
  podSelector:
    matchLabels:
      authentication-network: "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: localpvelection
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/jasna/PyCharmProjects/IEP/kubernetes/election/mysql"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: election-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeName: localpvelection
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: election-db-secret
type: Opaque
data:
  password: cm9vdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-db-deployment
  labels:
    app: election-db
    admin-network: "true"
    election-network: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: election-db
  template:
    metadata:
      labels:
        app: election-db
    spec:
      volumes:
        - name: election-db-storage
          persistentVolumeClaim:
            claimName: election-db-pvc
      containers:
        - name: election-db
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: election-db-secret
                  key: password
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: election-db-storage
---
apiVersion: v1
kind: Service
metadata:
  name: election-db-service
spec:
  selector:
    app: election-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: election-db-configmap
data:
  election-db-url: election-db-service
---
apiVersion: v1
kind: Pod
metadata:
  name: election-db-migration
  labels:
    election-network: "true"
spec:
  containers:
    - name: electiondbmigration
      image: electiondbmigration
      imagePullPolicy: IfNotPresent
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: election-db-configmap
              key: election-db-url
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer-deployment
    authentication-network: "true"
    election-network: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentication-db-secret
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: election-db-secret
                  key: password
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  type: LoadBalancer
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    admin-network: "true"
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: admin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: election-db-configmap
                  key: election-db-url
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: LoadBalancer
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: admin-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              admin-network: "true"
  podSelector:
    matchLabels:
      admin-network: "true"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: election-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              election-network: "true"
  podSelector:
    matchLabels:
      election-network: "true"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vote-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              vote-network: "true"
  podSelector:
    matchLabels:
      vote-network: "true"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              redis-network: "true"
  podSelector:
    matchLabels:
      redis-network: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: official-deployment
  labels:
    vote-network: "true"
    app: official
spec:
  replicas: 3
  selector:
    matchLabels:
      app: official
  template:
    metadata:
      labels:
        app: official
    spec:
      containers:
        - name: official
          image: official
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: REDIS_URI
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: official-service
spec:
  type: LoadBalancer
  selector:
    app: official
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daemon-deployment
  labels:
    app: daemon
    redis-network: "true"
    election-network: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daemon
  template:
    metadata:
      labels:
        app: daemon
    spec:
      containers:
        - name: daemon
          image: daemon
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: election-db-configmap
                  key: election-db-url
            - name: REDIS_URI
              value: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-deployment
    vote-network: "true"
    redis-network: "true"
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
